fix: test all file (#3)
* test: break stuff

* test: break stuff

* test: break stuff

* test: break stuff

* test: break stuff

* test: break stuff

* test: break stuff

* test: break stuff

* test: break stuff

* test: break stuff

* test: break stuff

* test: break stuff

* test: break stuff 2

* test: break stuff 2

* test: break stuff 2

* feat: check all files

* feat: check all files

* feat: check all files

* feat: check all files

* feat: check all files

* feat: check all files

* feat: fix file

diff --git a/.github/workflows/check_context_valid_json.yaml b/.github/workflows/check_context_valid_json.yaml
--- a/.github/workflows/check_context_valid_json.yaml
+++ b/.github/workflows/check_context_valid_json.yaml
@@ -23,8 +23,10 @@ jobs:
       - name: Check JSON-LD contexts
         run: |
           cd jsonld-contexts
+          error=0
           for file in $(find . -name "*.jsonld"); do
             printf "Checking $file .. "
-            jq empty $file && echo "OK"
-          done || exit 1
+            jq empty $file && echo "OK" || { error=1; echo "KO invalid JSON"; }
+          done
+          exit $error
         shell: bash
